Adicionado atributo hr_json em Produto
gleideveloper/gpd-plannig-tool pull request #117
Opened 2023-11-03 16:07 UTC by AndreXVR

#113

2023-11-04 05:42 UTC, gleideveloper requested changes
Andre ao fazer o teste deu erro ao tentar salvar o campo hr_json

![image](https://github.com/gleideveloper/gpd-plannig-tool/assets/5949025/8b7c11b6-12fa-4afb-9835-fab19de79461)

se basea na feature que fiz para alteração da modelo, segue abaixo:
- [ ] #112

2023-11-05 21:47 UTC, AndreXVR commented
> Andre ao fazer o teste deu erro ao tentar salvar o campo hr_json
> 
> ![image](https://user-images.githubusercontent.com/5949025/280448250-8b7c11b6-12fa-4afb-9835-fab19de79461.png)
> 
> se basea na feature que fiz para alteração da modelo, segue abaixo:
> 
> * [ ]  [feature/EndPointTemplate #112](https://github.com/gleideveloper/gpd-plannig-tool/issues/112)

![image](https://github.com/gleideveloper/gpd-plannig-tool/assets/57808599/dfcc44bd-8b9b-40b7-a170-3b59f66c56ef)
Valeu gleides, consegui corrigir

2023-11-06 22:06 UTC, gleideveloper approved these changes
testado

2023-11-06 22:22 UTC, NathSantos approved these changes

2023-11-06 22:23 UTC, gleideveloper approved these changes

2023-11-06 22:26 UTC, merged